/* tslint:disable */
/* eslint-disable */
/**
 * Authentication API
 * API for user authentication, including signup, login, token refresh, and logout.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  AuthResponse,
  LoginRequest,
  RefreshRequest,
  RegisterRequest,
  TokenResponse,
} from "../models/index";
import {
  AuthResponseFromJSON,
  AuthResponseToJSON,
  LoginRequestFromJSON,
  LoginRequestToJSON,
  RefreshRequestFromJSON,
  RefreshRequestToJSON,
  RegisterRequestFromJSON,
  RegisterRequestToJSON,
  TokenResponseFromJSON,
  TokenResponseToJSON,
} from "../models/index";

export interface LoginOperationRequest {
  loginRequest: LoginRequest;
}

export interface RefreshTokenRequest {
  refreshRequest: RefreshRequest;
}

export interface SignUpRequest {
  registerRequest: RegisterRequest;
}

/**
 *
 */
export class AuthenticationApi extends runtime.BaseAPI {
  /**
   * User login
   */
  async loginRaw(
    requestParameters: LoginOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthResponse>> {
    if (requestParameters["loginRequest"] == null) {
      throw new runtime.RequiredError(
        "loginRequest",
        'Required parameter "loginRequest" was null or undefined when calling login().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/auth/login`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: LoginRequestToJSON(requestParameters["loginRequest"]),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthResponseFromJSON(jsonValue)
    );
  }

  /**
   * User login
   */
  async login(
    requestParameters: LoginOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthResponse> {
    const response = await this.loginRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Logout user
   */
  async logoutRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/auth/logout`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Logout user
   */
  async logout(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.logoutRaw(initOverrides);
  }

  /**
   * Refresh access token
   */
  async refreshTokenRaw(
    requestParameters: RefreshTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TokenResponse>> {
    if (requestParameters["refreshRequest"] == null) {
      throw new runtime.RequiredError(
        "refreshRequest",
        'Required parameter "refreshRequest" was null or undefined when calling refreshToken().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/auth/refresh`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: RefreshRequestToJSON(requestParameters["refreshRequest"]),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TokenResponseFromJSON(jsonValue)
    );
  }

  /**
   * Refresh access token
   */
  async refreshToken(
    requestParameters: RefreshTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TokenResponse> {
    const response = await this.refreshTokenRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * User registration
   */
  async signUpRaw(
    requestParameters: SignUpRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthResponse>> {
    if (requestParameters["registerRequest"] == null) {
      throw new runtime.RequiredError(
        "registerRequest",
        'Required parameter "registerRequest" was null or undefined when calling signUp().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/auth/signup`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: RegisterRequestToJSON(requestParameters["registerRequest"]),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthResponseFromJSON(jsonValue)
    );
  }

  /**
   * User registration
   */
  async signUp(
    requestParameters: SignUpRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthResponse> {
    const response = await this.signUpRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
